# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1695b6a78ee8fea454a8fbd0a77733fdcb489088feb5c5eb17acb691e56e052c3a4792f9a2eea9ee9d187fcf03fb45c7341da5254bfc1e04eee2f345c3fcea69

test:
  secret_key_base: 5eb3c84a45866f3ce4f933175a0300286446f0413a70c2e302045ca368d0e066a307f1a953f737e0dad6f41dda9d474e052712c754d2449c17c7f28b2a14f4ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
